In [1]:
%load_ext sql

In [2]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")

In [3]:
df.head()

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing _Outcome
0,04-06-2010,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,08-12-2010,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,22-05-2012,07:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,08-10-2012,00:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,01-03-2013,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt

In [4]:
df['Date1']=df['Date']+' '+df['Time (UTC)']

In [5]:
df = df.drop('Date',axis=1)

In [6]:
df = df.drop('Time (UTC)',axis=1)

In [7]:
df.head()

,Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing _Outcome,Date1
0,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute),04-06-2010 18:45:00
1,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute),08-12-2010 15:43:00
2,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt,22-05-2012 07:44:00
3,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt,08-10-2012 00:35:00
4,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt,01-03-2013 15:10:00

In [8]:
first_column = df.pop('Date1')

In [9]:
df.insert(0,"Date1",first_column)

In [10]:
df['Date1'] = pd.to_datetime(df['Date1'], format='%d-%m-%Y %H:%M:%S')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date1              101 non-null    datetime64[ns]
 1   Booster_Version    101 non-null    object
 2   Launch_Site        101 non-null    object
 3   Payload            101 non-null    object
 4   PAYLOAD_MASS__KG_  101 non-null    int64
 5   Orbit              101 non-null    object
 6   Customer           101 non-null    object
 7   Mission_Outcome    101 non-null    object
 8   Landing _Outcome   101 non-null    object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 7.2+ KB

In [12]:
df.columns.str.len()

Int64Index([5, 15, 11, 7, 17, 5, 8, 15, 16], dtype='int64')

In [13]:
df.head()

,Date1,Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing _Outcome
0,2010-06-04 18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08 15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22 07:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08 00:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01 15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt

In [14]:
records_as_list = list(df.values)

records =[l.tolist() for l in records_as_list]

records

[[Timestamp('2010-06-04 18:45:00'),
  'F9 v1.0  B0003',
  'CCAFS LC-40',
  'Dragon Spacecraft Qualification Unit',
  0,
  'LEO',
  'SpaceX',
  'Success',
  'Failure (parachute)'],
 [Timestamp('2010-12-08 15:43:00'),
  'F9 v1.0  B0004',
  'CCAFS LC-40',
  'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese',
  0,
  'LEO (ISS)',
  'NASA (COTS) NRO',
  'Success',
  'Failure (parachute)'],
 [Timestamp('2012-05-22 07:44:00'),
  'F9 v1.0  B0005',
  'CCAFS LC-40',
  'Dragon demo flight C2',
  525,
  'LEO (ISS)',
  'NASA (COTS)',
  'Success',
  'No attempt'],
 [Timestamp('2012-10-08 00:35:00'),
  'F9 v1.0  B0006',
  'CCAFS LC-40',
  'SpaceX CRS-1',
  500,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'],
 [Timestamp('2013-03-01 15:10:00'),
  'F9 v1.0  B0007',
  'CCAFS LC-40',
  'SpaceX CRS-2',
  677,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'],
 [Timestamp('2013-09-29 16:00:00'),
  'F9 v1.1  B1003',
  'VAFB SLC-4E',
  'CASSIOPE',
  500,
  'Polar LEO',
  'MDA',
  'Success',
  'Uncontrolled (ocean)'],
 [Timestamp('2013-12-03 22:41:00'),
  'F9 v1.1',
  'CCAFS LC-40',
  'SES-8',
  3170,
  'GTO',
  'SES',
  'Success',
  'No attempt'],
 [Timestamp('2014-01-06 22:06:00'),
  'F9 v1.1',
  'CCAFS LC-40',
  'Thaicom 6',
  3325,
  'GTO',
  'Thaicom',
  'Success',
  'No attempt'],
 [Timestamp('2014-04-18 19:25:00'),
  'F9 v1.1',
  'CCAFS LC-40',
  'SpaceX CRS-3',
  2296,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Controlled (ocean)'],
 [Timestamp('2014-07-14 15:15:00'),
  'F9 v1.1',
  'CCAFS LC-40',
  'OG2 Mission 1  6 Orbcomm-OG2 satellites',
  1316,
  'LEO',
  'Orbcomm',
  'Success',
  'Controlled (ocean)'],
 [Timestamp('2014-08-05 08:00:00'),
  'F9 v1.1',
  'CCAFS LC-40',
  'AsiaSat 8',
  4535,
  'GTO',
  'AsiaSat',
  'Success',
  'No attempt'],
 [Timestamp('2014-09-07 05:00:00'),
  'F9 v1.1 B1011',
  'CCAFS LC-40',
  'AsiaSat 6',
  4428,
  'GTO',
  'AsiaSat',
  'Success',
  'No attempt'],
 [Timestamp('2014-09-21 05:52:00'),
  'F9 v1.1 B1010',
  'CCAFS LC-40',
  'SpaceX CRS-4',
  2216,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Uncontrolled (ocean)'],
 [Timestamp('2015-01-10 09:47:00'),
  'F9 v1.1 B1012',
  'CCAFS LC-40',
  'SpaceX CRS-5',
  2395,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Failure (drone ship)'],
 [Timestamp('2015-02-11 23:03:00'),
  'F9 v1.1 B1013',
  'CCAFS LC-40',
  'DSCOVR',
  570,
  'HEO',
  'U.S. Air Force NASA NOAA',
  'Success',
  'Controlled (ocean)'],
 [Timestamp('2015-03-02 03:50:00'),
  'F9 v1.1 B1014',
  'CCAFS LC-40',
  'ABS-3A Eutelsat 115 West B',
  4159,
  'GTO',
  'ABS Eutelsat',
  'Success',
  'No attempt'],
 [Timestamp('2015-04-14 20:10:00'),
  'F9 v1.1 B1015',
  'CCAFS LC-40',
  'SpaceX CRS-6',
  1898,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Failure (drone ship)'],
 [Timestamp('2015-04-27 23:03:00'),
  'F9 v1.1 B1016',
  'CCAFS LC-40',
  'Turkmen 52 / MonacoSAT',
  4707,
  'GTO',
  'Turkmenistan National Space Agency',
  'Success',
  'No attempt'],
 [Timestamp('2015-06-28 14:21:00'),
  'F9 v1.1 B1018',
  'CCAFS LC-40',
  'SpaceX CRS-7',
  1952,
  'LEO (ISS)',
  'NASA (CRS)',
  'Failure (in flight)',
  'Precluded (drone ship)'],
 [Timestamp('2015-12-22 01:29:00'),
  'F9 FT B1019',
  'CCAFS LC-40',
  'OG2 Mission 2  11 Orbcomm-OG2 satellites',
  2034,
  'LEO',
  'Orbcomm',
  'Success',
  'Success (ground pad)'],
 [Timestamp('2016-01-17 18:42:00'),
  'F9 v1.1 B1017',
  'VAFB SLC-4E',
  'Jason-3',
  553,
  'LEO',
  'NASA (LSP) NOAA CNES',
  'Success',
  'Failure (drone ship)'],
 [Timestamp('2016-03-04 23:35:00'),
  'F9 FT B1020',
  'CCAFS LC-40',
  'SES-9',
  5271,
  'GTO',
  'SES',
  'Success',
  'Failure (drone ship)'],
 [Timestamp('2016-04-08 20:43:00'),
  'F9 FT B1021.1',
  'CCAFS LC-40',
  'SpaceX CRS-8',
  3136,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2016-05-06 05:21:00'),
  'F9 FT B1022',
  'CCAFS LC-40',
  'JCSAT-14',
  4696,
  'GTO',
  'SKY Perfect JSAT Group',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2016-05-27 21:39:00'),
  'F9 FT B1023.1',
  'CCAFS LC-40',
  'Thaicom 8',
  3100,
  'GTO',
  'Thaicom',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2016-06-15 14:29:00'),
  'F9 FT B1024',
  'CCAFS LC-40',
  'ABS-2A Eutelsat 117 West B',
  3600,
  'GTO',
  'ABS Eutelsat',
  'Success',
  'Failure (drone ship)'],
 [Timestamp('2016-07-18 04:45:00'),
  'F9 FT B1025.1',
  'CCAFS LC-40',
  'SpaceX CRS-9',
  2257,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (ground pad)'],
 [Timestamp('2016-08-14 05:26:00'),
  'F9 FT B1026',
  'CCAFS LC-40',
  'JCSAT-16',
  4600,
  'GTO',
  'SKY Perfect JSAT Group',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2017-01-14 17:54:00'),
  'F9 FT B1029.1',
  'VAFB SLC-4E',
  'Iridium NEXT 1',
  9600,
  'Polar LEO',
  'Iridium Communications',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2017-02-19 14:39:00'),
  'F9 FT B1031.1',
  'KSC LC-39A',
  'SpaceX CRS-10',
  2490,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (ground pad)'],
 [Timestamp('2017-03-16 06:00:00'),
  'F9 FT B1030',
  'KSC LC-39A',
  'EchoStar 23',
  5600,
  'GTO',
  'EchoStar',
  'Success',
  'No attempt'],
 [Timestamp('2017-03-30 22:27:00'),
  'F9 FT  B1021.2',
  'KSC LC-39A',
  'SES-10',
  5300,
  'GTO',
  'SES',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2017-05-01 11:15:00'),
  'F9 FT B1032.1',
  'KSC LC-39A',
  'NROL-76',
  5300,
  'LEO',
  'NRO',
  'Success',
  'Success (ground pad)'],
 [Timestamp('2017-05-15 23:21:00'),
  'F9 FT B1034',
  'KSC LC-39A',
  'Inmarsat-5 F4',
  6070,
  'GTO',
  'Inmarsat',
  'Success',
  'No attempt'],
 [Timestamp('2017-06-03 21:07:00'),
  'F9 FT B1035.1',
  'KSC LC-39A',
  'SpaceX CRS-11',
  2708,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (ground pad)'],
 [Timestamp('2017-06-23 19:10:00'),
  'F9 FT  B1029.2',
  'KSC LC-39A',
  'BulgariaSat-1',
  3669,
  'GTO',
  'Bulsatcom',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2017-06-25 20:25:00'),
  'F9 FT B1036.1',
  'VAFB SLC-4E',
  'Iridium NEXT 2',
  9600,
  'LEO',
  'Iridium Communications',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2017-07-05 23:38:00'),
  'F9 FT B1037',
  'KSC LC-39A',
  'Intelsat 35e',
  6761,
  'GTO',
  'Intelsat',
  'Success',
  'No attempt'],
 [Timestamp('2017-08-14 16:31:00'),
  'F9 B4 B1039.1',
  'KSC LC-39A',
  'SpaceX CRS-12',
  3310,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (ground pad)'],
 [Timestamp('2017-08-24 18:51:00'),
  'F9 FT B1038.1',
  'VAFB SLC-4E',
  'Formosat-5',
  475,
  'SSO',
  'NSPO',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2017-09-07 14:00:00'),
  'F9 B4 B1040.1',
  'KSC LC-39A',
  'Boeing X-37B OTV-5',
  4990,
  'LEO',
  'U.S. Air Force',
  'Success',
  'Success (ground pad)'],
 [Timestamp('2017-10-09 12:37:00'),
  'F9 B4 B1041.1',
  'VAFB SLC-4E',
  'Iridium NEXT 3',
  9600,
  'Polar LEO',
  'Iridium Communications',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2017-10-11 22:53:00'),
  'F9 FT  B1031.2',
  'KSC LC-39A',
  'SES-11 / EchoStar 105',
  5200,
  'GTO',
  'SES EchoStar',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2017-10-30 19:34:00'),
  'F9 B4 B1042.1',
  'KSC LC-39A',
  'Koreasat 5A',
  3500,
  'GTO',
  'KT Corporation',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2017-12-15 15:36:00'),
  'F9 FT  B1035.2',
  'CCAFS SLC-40',
  'SpaceX CRS-13',
  2205,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (ground pad)'],
 [Timestamp('2017-12-23 01:27:00'),
  'F9 FT  B1036.2',
  'VAFB SLC-4E',
  'Iridium NEXT 4',
  9600,
  'Polar LEO',
  'Iridium Communications',
  'Success',
  'Controlled (ocean)'],
 [Timestamp('2018-01-08 01:00:00'),
  'F9 B4 B1043.1',
  'CCAFS SLC-40',
  'Zuma',
  5000,
  'LEO',
  'Northrop Grumman',
  'Success (payload status unclear)',
  'Success (ground pad)'],
 [Timestamp('2018-01-31 21:25:00'),
  'F9 FT  B1032.2',
  'CCAFS SLC-40',
  'GovSat-1 / SES-16',
  4230,
  'GTO',
  'SES',
  'Success',
  'Controlled (ocean)'],
 [Timestamp('2018-02-22 14:17:00'),
  'F9 FT  B1038.2',
  'VAFB SLC-4E',
  'Paz  Tintin A & B',
  2150,
  'SSO',
  'Hisdesat exactEarth SpaceX',
  'Success',
  'No attempt'],
 [Timestamp('2018-03-06 05:33:00'),
  'F9 B4 B1044',
  'CCAFS SLC-40',
  'Hispasat 30W-6  PODSat',
  6092,
  'GTO',
  'Hispasat  NovaWurks',
  'Success',
  'No attempt'],
 [Timestamp('2018-03-30 14:14:00'),
  'F9 B4  B1041.2',
  'VAFB SLC-4E',
  'Iridium NEXT 5',
  9600,
  'Polar LEO',
  'Iridium Communications',
  'Success',
  'No attempt'],
 [Timestamp('2018-04-02 20:30:00'),
  'F9 B4  B1039.2',
  'CCAFS SLC-40',
  'SpaceX CRS-14',
  2647,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'],
 [Timestamp('2018-04-18 22:51:00'),
  'F9 B4 B1045.1',
  'CCAFS SLC-40',
  'Transiting Exoplanet Survey Satellite (TESS)',
  362,
  'HEO',
  'NASA (LSP)',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2018-05-11 20:14:00'),
  'F9 B5  B1046.1',
  'KSC LC-39A',
  'Bangabandhu-1',
  3600,
  'GTO',
  'Thales-Alenia/BTRC',
  'Success',
  'Success (drone ship)'],
 [Timestamp('2018-05-22 19:47:58'),
  'F9 B4  B1043.2',
  'VAFB SLC-4E',
  'Iridium NEXT 6   GRACE-FO 1, 2',
  6460,
  'Polar LEO',
  'Iridium Communications GFZ ‚ NASA',
  'Success',
  'No attempt'],
 [Timestamp('2018-06-04 04:45:00'),
  'F9 B4  B1040.2',
  'CCAFS SLC-40',
  'SES-12',
  5384,
  'GTO',
  'SES',
  'Success',
  'No attempt'],
 [Timestamp('2018-06-29 09:42:00'),
  'F9 B4 B1045.2',
  'CCAFS SLC-40',
  'SpaceX CRS-15',
  2697,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'],
 [Timestamp('2018-07-22 05:50:00'),
  'F9 B5B1047.1',
  'CCAFS SLC-40',
  'Telstar 19V',
  7075,
  'GTO',
  'Telesat',
  'Success',
  'Success'],
 [Timestamp('2018-07-25 11:39:00'),
  'F9 B5B1048.1',
  'VAFB SLC-4E',
  'Iridium NEXT-7',
  9600,
  'Polar LEO',
  'Iridium Communications',
  'Success',
  'Success'],
 [Timestamp('2018-08-07 05:18:00'),
  'F9 B5 B1046.2',
  'CCAFS SLC-40',
  'Merah Putih ',
  5800,
  'GTO',
  'Telkom Indonesia',
  'Success',
  'Success'],
 [Timestamp('2018-09-10 04:45:00'),
  'F9 B5B1049.1',
  'CCAFS SLC-40',
  'Telstar 18V / Apstar-5C',
  7060,
  'GTO',
  'Telesat',
  'Success',
  'Success'],
 [Timestamp('2018-10-08 02:22:00'),
  'F9 B5 B1048.2',
  'VAFB SLC-4E',
  'SAOCOM 1A',
  3000,
  'SSO',
  'CONAE',
  'Success',
  'Success'],
 [Timestamp('2018-11-15 20:46:00'),
  'F9 B5 B1047.2',
  'KSC LC-39A',
  'Es hail 2',
  5300,
  'GTO',
  'Es hailSat',
  'Success',
  'Success'],
 [Timestamp('2018-12-03 18:34:05'),
  'F9 B5 B1046.3',
  'VAFB SLC-4E',
  'SSO-A ',
  4000,
  'SSO',
  'Spaceflight Industries',
  'Success',
  'Success'],
 [Timestamp('2018-12-05 18:16:00'),
  'F9 B5B1050',
  'CCAFS SLC-40',
  'SpaceX CRS-16',
  2500,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Failure'],
 [Timestamp('2018-12-23 13:51:00'),
  'F9 B5B1054',
  'CCAFS SLC-40',
  'GPS III-01 ',
  4400,
  'MEO',
  'USAF',
  'Success ',
  'No attempt'],
 [Timestamp('2019-01-11 15:31:00'),
  'F9 B5 B1049.2',
  'VAFB SLC-4E',
  'Iridium NEXT-8',
  9600,
  'Polar LEO',
  'Iridium Communications',
  'Success',
  'Success'],
 [Timestamp('2019-02-22 01:45:00'),
  'F9 B5 B1048.3',
  'CCAFS SLC-40',
  'Nusantara Satu, Beresheet Moon lander, S5',
  4850,
  'GTO',
  'PSN, SpaceIL / IAI',
  'Success',
  'Success'],
 [Timestamp('2019-03-02 07:49:00'),
  'F9 B5B1051.1',
  'KSC LC-39A',
  'Crew Dragon Demo-1, SpaceX CRS-17 ',
  12055,
  'LEO (ISS)',
  'NASA (CCD) ',
  'Success',
  'Success'],
 [Timestamp('2019-05-04 06:48:00'),
  'F9 B5B1056.1 ',
  'CCAFS SLC-40',
  'SpaceX CRS-17, Starlink v0.9',
  2495,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success'],
 [Timestamp('2019-05-24 02:30:00'),
  'F9 B5 B1049.3',
  'CCAFS SLC-40',
  'Starlink v0.9, RADARSAT Constellation',
  13620,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2019-06-12 14:17:00'),
  'F9 B5 B1051.2 ',
  'VAFB SLC-4E',
  'RADARSAT Constellation, SpaceX CRS-18 ',
  4200,
  'SSO',
  'Canadian Space Agency (CSA)',
  'Success',
  'Success'],
 [Timestamp('2019-07-25 22:01:00'),
  'F9 B5 B1056.2 ',
  'CCAFS SLC-40',
  'SpaceX CRS-18, AMOS-17 ',
  2268,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success'],
 [Timestamp('2019-08-06 23:23:00'),
  'F9 B5 B1047.3 ',
  'CCAFS SLC-40',
  'AMOS-17, Starlink 1 v1.0 ',
  6500,
  'GTO',
  'Spacecom',
  'Success',
  'No attempt '],
 [Timestamp('2019-11-11 14:56:00'),
  'F9 B5 B1048.4',
  'CCAFS SLC-40',
  'Starlink 1 v1.0, SpaceX CRS-19 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2019-12-05 17:29:00'),
  'F9 B5B1059.1',
  'CCAFS SLC-40',
  'SpaceX CRS-19, JCSat-18 / Kacific 1 ',
  2617,
  'LEO (ISS)',
  'NASA (CRS), Kacific 1',
  'Success',
  'Success'],
 [Timestamp('2019-12-17 00:10:00'),
  'F9 B5 B1056.3 ',
  'CCAFS SLC-40',
  'JCSat-18 / Kacific 1, Starlink 2 v1.0 ',
  6956,
  'GTO',
  'Sky Perfect JSAT, Kacific 1',
  'Success',
  'Success'],
 [Timestamp('2020-01-07 02:33:00'),
  'F9 B5 B1049.4',
  'CCAFS SLC-40',
  'Starlink 2 v1.0, Crew Dragon in-flight abort test ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2020-01-19 15:30:00'),
  'F9 B5 B1046.4',
  'KSC LC-39A',
  'Crew Dragon in-flight abort test, Starlink 3 v1.0 ',
  12050,
  'Sub-orbital',
  'NASA (CTS)',
  'Success',
  'No attempt'],
 [Timestamp('2020-01-29 14:07:00'),
  'F9 B5 B1051.3',
  'CCAFS SLC-40',
  'Starlink 3 v1.0, Starlink 4 v1.0 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2020-02-17 15:05:00'),
  'F9 B5 B1056.4',
  'CCAFS SLC-40',
  'Starlink 4 v1.0, SpaceX CRS-20',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Failure'],
 [Timestamp('2020-03-07 04:50:00'),
  'F9 B5 B1059.2',
  'CCAFS SLC-40',
  'SpaceX CRS-20, Starlink 5 v1.0 ',
  1977,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success'],
 [Timestamp('2020-03-18 12:16:00'),
  'F9 B5 B1048.5',
  'KSC LC-39A',
  'Starlink 5 v1.0, Starlink 6 v1.0 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Failure'],
 [Timestamp('2020-04-22 19:30:00'),
  'F9 B5 B1051.4',
  'KSC LC-39A',
  'Starlink 6 v1.0, Crew Dragon Demo-2 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2020-05-30 19:22:00'),
  'F9 B5B1058.1 ',
  'KSC LC-39A',
  'Crew Dragon Demo-2, Starlink 7 v1.0 ',
  12530,
  'LEO (ISS)',
  'NASA (CCDev)',
  'Success',
  'Success'],
 [Timestamp('2020-06-04 01:25:00'),
  'F9 B5 B1049.5',
  'CCAFS SLC-40',
  'Starlink 7 v1.0, Starlink 8 v1.0',
  15600,
  'LEO',
  'SpaceX, Planet Labs',
  'Success',
  'Success'],
 [Timestamp('2020-06-13 09:21:00'),
  'F9 B5 B1059.3',
  'CCAFS SLC-40',
  'Starlink 8 v1.0, SkySats-16, -17, -18, GPS III-03 ',
  15410,
  'LEO',
  'SpaceX, Planet Labs',
  'Success',
  'Success'],
 [Timestamp('2020-06-30 20:10:46'),
  'F9 B5B1060.1',
  'CCAFS SLC-40',
  'GPS III-03, ANASIS-II',
  4311,
  'MEO',
  'U.S. Space Force',
  'Success',
  'Success'],
 [Timestamp('2020-07-20 21:30:00'),
  'F9 B5 B1058.2 ',
  'CCAFS SLC-40',
  'ANASIS-II, Starlink 9 v1.0',
  5500,
  'GTO',
  'Republic of Korea Army, Spaceflight Industries (BlackSky)',
  'Success',
  'Success'],
 [Timestamp('2020-08-07 05:12:00'),
  'F9 B5 B1051.5',
  'KSC LC-39A',
  'Starlink 9 v1.0, SXRS-1, Starlink 10 v1.0 ',
  14932,
  'LEO',
  'SpaceX, Spaceflight Industries (BlackSky), Planet Labs',
  'Success',
  'Success'],
 [Timestamp('2020-08-18 14:31:00'),
  'F9 B5 B1049.6',
  'CCAFS SLC-40',
  'Starlink 10 v1.0, SkySat-19, -20, -21, SAOCOM 1B ',
  15440,
  'LEO',
  'SpaceX, Planet Labs, PlanetIQ',
  'Success',
  'Success'],
 [Timestamp('2020-08-30 23:18:00'),
  'F9 B5 B1059.4',
  'CCAFS SLC-40',
  'SAOCOM 1B, GNOMES 1, Tyvak-0172',
  3130,
  'SSO',
  'CONAE, PlanetIQ, SpaceX',
  'Success',
  'Success'],
 [Timestamp('2020-09-03 12:46:14'),
  'F9 B5 B1060.2 ',
  'KSC LC-39A',
  'Starlink 11 v1.0, Starlink 12 v1.0 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2020-10-06 11:29:34'),
  'F9 B5 B1058.3 ',
  'KSC LC-39A',
  'Starlink 12 v1.0, Starlink 13 v1.0 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2020-10-18 12:25:57'),
  'F9 B5 B1051.6',
  'KSC LC-39A',
  'Starlink 13 v1.0, Starlink 14 v1.0 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2020-10-24 15:31:34'),
  'F9 B5 B1060.3',
  'CCAFS SLC-40',
  'Starlink 14 v1.0, GPS III-04  ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2020-11-05 23:24:23'),
  'F9 B5B1062.1',
  'CCAFS SLC-40',
  'GPS III-04 , Crew-1',
  4311,
  'MEO',
  'USSF',
  'Success',
  'Success'],
 [Timestamp('2020-11-16 00:27:00'),
  'F9 B5B1061.1 ',
  'KSC LC-39A',
  'Crew-1, Sentinel-6 Michael Freilich ',
  12500,
  'LEO (ISS)',
  'NASA (CCP)',
  'Success',
  'Success'],
 [Timestamp('2020-11-21 17:17:08'),
  'F9 B5B1063.1',
  'VAFB SLC-4E',
  'Sentinel-6 Michael Freilich, Starlink 15 v1.0 ',
  1192,
  'LEO',
  'NASA / NOAA / ESA / EUMETSAT',
  'Success',
  'Success'],
 [Timestamp('2020-11-25 02:13:00'),
  'F9 B5 B1049.7 ',
  'CCAFS SLC-40',
  'Starlink 15 v1.0, SpaceX CRS-21',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'],
 [Timestamp('2020-12-06 16:17:08'),
  'F9 B5 B1058.4 ',
  'KSC LC-39A',
  'SpaceX CRS-21',
  2972,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success']]

In [17]:
import cx_Oracle
con = cx_Oracle.connect('practice/practice@localhost:1521/xe')
    # Now execute the sqlquery
cursor = con.cursor()
 
    # drop a table employee
cursor.execute("drop table spacextbl")

In [18]:
import cx_Oracle
 
# Create a table in Oracle database
try:
 
    con = cx_Oracle.connect('practice/practice@localhost:1521/xe')
    print(con.version)
 
    # Now execute the sqlquery
    cursor = con.cursor()
 
    # Creating a table employee
    cursor.execute(
        "create table spacextbl(date1 date, Booster_Version varchar(20), Launch_Site varchar(40), Payload varchar(100), PAYLOAD_MASS__KG_ number(38), Orbit varchar(40), Customer varchar(100), Mission_Outcome varchar(40), Landing_Outcome varchar(40))")
 
    print("Table Created successfully")
 
except cx_Oracle.DatabaseError as e:
    print("There is a problem with Oracle", e)
 
# by writing finally if any error occurs
# then also we can close the all database operation
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()

11.2.0.2.0
Table Created successfully

In [19]:
import cx_Oracle
 
# Load data from a csv file into Oracle table using executemany
try:
    con = cx_Oracle.connect('practice/practice@localhost:1521/xe')
 
except cx_Oracle.DatabaseError as er:
    print('There is an error in Oracle database:', er)
 
else:
    try:
        cur = con.cursor()
        data = records
 
        cur = con.cursor()
        # Inserting multiple records into employee table
        # (:1,:2,:3) are place holders. They pick data from a list supplied as argument
        cur.executemany('insert into spacextbl values(:1,:2,:3,:4,:5,:6,:7,:8,:9)', data)
 
    except cx_Oracle.DatabaseError as er:
        print('There is an error in Oracle database:', er)
 
    except Exception as er:
        print(er)
 
    else:
        # To commit the transaction manually
        con.commit()
        print('Multiple records are inserted successfully')
 
finally:
    if cur:
        cur.close()
    if con:
        con.close()

Multiple records are inserted successfully

In [20]:
%sql oracle://practice:practice@localhost:1521/xe

In [21]:
%sql

 * oracle://practice:***@localhost:1521/xe

In [22]:
%sql select * from spacextbl

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[(datetime.datetime(2010, 6, 4, 18, 45), 'F9 v1.0  B0003', 'CCAFS LC-40', 'Dragon Spacecraft Qualification Unit', 0, 'LEO', 'SpaceX', 'Success', 'Failure (parachute)'),
 (datetime.datetime(2010, 12, 8, 15, 43), 'F9 v1.0  B0004', 'CCAFS LC-40', 'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese', 0, 'LEO (ISS)', 'NASA (COTS) NRO', 'Success', 'Failure (parachute)'),
 (datetime.datetime(2012, 5, 22, 7, 44), 'F9 v1.0  B0005', 'CCAFS LC-40', 'Dragon demo flight C2', 525, 'LEO (ISS)', 'NASA (COTS)', 'Success', 'No attempt'),
 (datetime.datetime(2012, 10, 8, 0, 35), 'F9 v1.0  B0006', 'CCAFS LC-40', 'SpaceX CRS-1', 500, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt'),
 (datetime.datetime(2013, 3, 1, 15, 10), 'F9 v1.0  B0007', 'CCAFS LC-40', 'SpaceX CRS-2', 677, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt'),
 (datetime.datetime(2013, 9, 29, 16, 0), 'F9 v1.1  B1003', 'VAFB SLC-4E', 'CASSIOPE', 500, 'Polar LEO', 'MDA', 'Success', 'Uncontrolled (ocean)'),
 (datetime.datetime(2013, 12, 3, 22, 41), 'F9 v1.1', 'CCAFS LC-40', 'SES-8', 3170, 'GTO', 'SES', 'Success', 'No attempt'),
 (datetime.datetime(2014, 1, 6, 22, 6), 'F9 v1.1', 'CCAFS LC-40', 'Thaicom 6', 3325, 'GTO', 'Thaicom', 'Success', 'No attempt'),
 (datetime.datetime(2014, 4, 18, 19, 25), 'F9 v1.1', 'CCAFS LC-40', 'SpaceX CRS-3', 2296, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Controlled (ocean)'),
 (datetime.datetime(2014, 7, 14, 15, 15), 'F9 v1.1', 'CCAFS LC-40', 'OG2 Mission 1  6 Orbcomm-OG2 satellites', 1316, 'LEO', 'Orbcomm', 'Success', 'Controlled (ocean)'),
 (datetime.datetime(2014, 8, 5, 8, 0), 'F9 v1.1', 'CCAFS LC-40', 'AsiaSat 8', 4535, 'GTO', 'AsiaSat', 'Success', 'No attempt'),
 (datetime.datetime(2014, 9, 7, 5, 0), 'F9 v1.1 B1011', 'CCAFS LC-40', 'AsiaSat 6', 4428, 'GTO', 'AsiaSat', 'Success', 'No attempt'),
 (datetime.datetime(2014, 9, 21, 5, 52), 'F9 v1.1 B1010', 'CCAFS LC-40', 'SpaceX CRS-4', 2216, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Uncontrolled (ocean)'),
 (datetime.datetime(2015, 1, 10, 9, 47), 'F9 v1.1 B1012', 'CCAFS LC-40', 'SpaceX CRS-5', 2395, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Failure (drone ship)'),
 (datetime.datetime(2015, 2, 11, 23, 3), 'F9 v1.1 B1013', 'CCAFS LC-40', 'DSCOVR', 570, 'HEO', 'U.S. Air Force NASA NOAA', 'Success', 'Controlled (ocean)'),
 (datetime.datetime(2015, 3, 2, 3, 50), 'F9 v1.1 B1014', 'CCAFS LC-40', 'ABS-3A Eutelsat 115 West B', 4159, 'GTO', 'ABS Eutelsat', 'Success', 'No attempt'),
 (datetime.datetime(2015, 4, 14, 20, 10), 'F9 v1.1 B1015', 'CCAFS LC-40', 'SpaceX CRS-6', 1898, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Failure (drone ship)'),
 (datetime.datetime(2015, 4, 27, 23, 3), 'F9 v1.1 B1016', 'CCAFS LC-40', 'Turkmen 52 / MonacoSAT', 4707, 'GTO', 'Turkmenistan National Space Agency', 'Success', 'No attempt'),
 (datetime.datetime(2015, 6, 28, 14, 21), 'F9 v1.1 B1018', 'CCAFS LC-40', 'SpaceX CRS-7', 1952, 'LEO (ISS)', 'NASA (CRS)', 'Failure (in flight)', 'Precluded (drone ship)'),
 (datetime.datetime(2015, 12, 22, 1, 29), 'F9 FT B1019', 'CCAFS LC-40', 'OG2 Mission 2  11 Orbcomm-OG2 satellites', 2034, 'LEO', 'Orbcomm', 'Success', 'Success (ground pad)'),
 (datetime.datetime(2016, 1, 17, 18, 42), 'F9 v1.1 B1017', 'VAFB SLC-4E', 'Jason-3', 553, 'LEO', 'NASA (LSP) NOAA CNES', 'Success', 'Failure (drone ship)'),
 (datetime.datetime(2016, 3, 4, 23, 35), 'F9 FT B1020', 'CCAFS LC-40', 'SES-9', 5271, 'GTO', 'SES', 'Success', 'Failure (drone ship)'),
 (datetime.datetime(2016, 4, 8, 20, 43), 'F9 FT B1021.1', 'CCAFS LC-40', 'SpaceX CRS-8', 3136, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2016, 5, 6, 5, 21), 'F9 FT B1022', 'CCAFS LC-40', 'JCSAT-14', 4696, 'GTO', 'SKY Perfect JSAT Group', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2016, 5, 27, 21, 39), 'F9 FT B1023.1', 'CCAFS LC-40', 'Thaicom 8', 3100, 'GTO', 'Thaicom', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2016, 6, 15, 14, 29), 'F9 FT B1024', 'CCAFS LC-40', 'ABS-2A Eutelsat 117 West B', 3600, 'GTO', 'ABS Eutelsat', 'Success', 'Failure (drone ship)'),
 (datetime.datetime(2016, 7, 18, 4, 45), 'F9 FT B1025.1', 'CCAFS LC-40', 'SpaceX CRS-9', 2257, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success (ground pad)'),
 (datetime.datetime(2016, 8, 14, 5, 26), 'F9 FT B1026', 'CCAFS LC-40', 'JCSAT-16', 4600, 'GTO', 'SKY Perfect JSAT Group', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2017, 1, 14, 17, 54), 'F9 FT B1029.1', 'VAFB SLC-4E', 'Iridium NEXT 1', 9600, 'Polar LEO', 'Iridium Communications', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2017, 2, 19, 14, 39), 'F9 FT B1031.1', 'KSC LC-39A', 'SpaceX CRS-10', 2490, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success (ground pad)'),
 (datetime.datetime(2017, 3, 16, 6, 0), 'F9 FT B1030', 'KSC LC-39A', 'EchoStar 23', 5600, 'GTO', 'EchoStar', 'Success', 'No attempt'),
 (datetime.datetime(2017, 3, 30, 22, 27), 'F9 FT  B1021.2', 'KSC LC-39A', 'SES-10', 5300, 'GTO', 'SES', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2017, 5, 1, 11, 15), 'F9 FT B1032.1', 'KSC LC-39A', 'NROL-76', 5300, 'LEO', 'NRO', 'Success', 'Success (ground pad)'),
 (datetime.datetime(2017, 5, 15, 23, 21), 'F9 FT B1034', 'KSC LC-39A', 'Inmarsat-5 F4', 6070, 'GTO', 'Inmarsat', 'Success', 'No attempt'),
 (datetime.datetime(2017, 6, 3, 21, 7), 'F9 FT B1035.1', 'KSC LC-39A', 'SpaceX CRS-11', 2708, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success (ground pad)'),
 (datetime.datetime(2017, 6, 23, 19, 10), 'F9 FT  B1029.2', 'KSC LC-39A', 'BulgariaSat-1', 3669, 'GTO', 'Bulsatcom', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2017, 6, 25, 20, 25), 'F9 FT B1036.1', 'VAFB SLC-4E', 'Iridium NEXT 2', 9600, 'LEO', 'Iridium Communications', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2017, 7, 5, 23, 38), 'F9 FT B1037', 'KSC LC-39A', 'Intelsat 35e', 6761, 'GTO', 'Intelsat', 'Success', 'No attempt'),
 (datetime.datetime(2017, 8, 14, 16, 31), 'F9 B4 B1039.1', 'KSC LC-39A', 'SpaceX CRS-12', 3310, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success (ground pad)'),
 (datetime.datetime(2017, 8, 24, 18, 51), 'F9 FT B1038.1', 'VAFB SLC-4E', 'Formosat-5', 475, 'SSO', 'NSPO', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2017, 9, 7, 14, 0), 'F9 B4 B1040.1', 'KSC LC-39A', 'Boeing X-37B OTV-5', 4990, 'LEO', 'U.S. Air Force', 'Success', 'Success (ground pad)'),
 (datetime.datetime(2017, 10, 9, 12, 37), 'F9 B4 B1041.1', 'VAFB SLC-4E', 'Iridium NEXT 3', 9600, 'Polar LEO', 'Iridium Communications', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2017, 10, 11, 22, 53), 'F9 FT  B1031.2', 'KSC LC-39A', 'SES-11 / EchoStar 105', 5200, 'GTO', 'SES EchoStar', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2017, 10, 30, 19, 34), 'F9 B4 B1042.1', 'KSC LC-39A', 'Koreasat 5A', 3500, 'GTO', 'KT Corporation', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2017, 12, 15, 15, 36), 'F9 FT  B1035.2', 'CCAFS SLC-40', 'SpaceX CRS-13', 2205, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success (ground pad)'),
 (datetime.datetime(2017, 12, 23, 1, 27), 'F9 FT  B1036.2', 'VAFB SLC-4E', 'Iridium NEXT 4', 9600, 'Polar LEO', 'Iridium Communications', 'Success', 'Controlled (ocean)'),
 (datetime.datetime(2018, 1, 8, 1, 0), 'F9 B4 B1043.1', 'CCAFS SLC-40', 'Zuma', 5000, 'LEO', 'Northrop Grumman', 'Success (payload status unclear)', 'Success (ground pad)'),
 (datetime.datetime(2018, 1, 31, 21, 25), 'F9 FT  B1032.2', 'CCAFS SLC-40', 'GovSat-1 / SES-16', 4230, 'GTO', 'SES', 'Success', 'Controlled (ocean)'),
 (datetime.datetime(2018, 2, 22, 14, 17), 'F9 FT  B1038.2', 'VAFB SLC-4E', 'Paz  Tintin A & B', 2150, 'SSO', 'Hisdesat exactEarth SpaceX', 'Success', 'No attempt'),
 (datetime.datetime(2018, 3, 6, 5, 33), 'F9 B4 B1044', 'CCAFS SLC-40', 'Hispasat 30W-6  PODSat', 6092, 'GTO', 'Hispasat  NovaWurks', 'Success', 'No attempt'),
 (datetime.datetime(2018, 3, 30, 14, 14), 'F9 B4  B1041.2', 'VAFB SLC-4E', 'Iridium NEXT 5', 9600, 'Polar LEO', 'Iridium Communications', 'Success', 'No attempt'),
 (datetime.datetime(2018, 4, 2, 20, 30), 'F9 B4  B1039.2', 'CCAFS SLC-40', 'SpaceX CRS-14', 2647, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt'),
 (datetime.datetime(2018, 4, 18, 22, 51), 'F9 B4 B1045.1', 'CCAFS SLC-40', 'Transiting Exoplanet Survey Satellite (TESS)', 362, 'HEO', 'NASA (LSP)', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2018, 5, 11, 20, 14), 'F9 B5  B1046.1', 'KSC LC-39A', 'Bangabandhu-1', 3600, 'GTO', 'Thales-Alenia/BTRC', 'Success', 'Success (drone ship)'),
 (datetime.datetime(2018, 5, 22, 19, 47, 58), 'F9 B4  B1043.2', 'VAFB SLC-4E', 'Iridium NEXT 6   GRACE-FO 1, 2', 6460, 'Polar LEO', 'Iridium Communications GFZ ‚ NASA', 'Success', 'No attempt'),
 (datetime.datetime(2018, 6, 4, 4, 45), 'F9 B4  B1040.2', 'CCAFS SLC-40', 'SES-12', 5384, 'GTO', 'SES', 'Success', 'No attempt'),
 (datetime.datetime(2018, 6, 29, 9, 42), 'F9 B4 B1045.2', 'CCAFS SLC-40', 'SpaceX CRS-15', 2697, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt'),
 (datetime.datetime(2018, 7, 22, 5, 50), 'F9 B5B1047.1', 'CCAFS SLC-40', 'Telstar 19V', 7075, 'GTO', 'Telesat', 'Success', 'Success'),
 (datetime.datetime(2018, 7, 25, 11, 39), 'F9 B5B1048.1', 'VAFB SLC-4E', 'Iridium NEXT-7', 9600, 'Polar LEO', 'Iridium Communications', 'Success', 'Success'),
 (datetime.datetime(2018, 8, 7, 5, 18), 'F9 B5 B1046.2', 'CCAFS SLC-40', 'Merah Putih ', 5800, 'GTO', 'Telkom Indonesia', 'Success', 'Success'),
 (datetime.datetime(2018, 9, 10, 4, 45), 'F9 B5B1049.1', 'CCAFS SLC-40', 'Telstar 18V / Apstar-5C', 7060, 'GTO', 'Telesat', 'Success', 'Success'),
 (datetime.datetime(2018, 10, 8, 2, 22), 'F9 B5 B1048.2', 'VAFB SLC-4E', 'SAOCOM 1A', 3000, 'SSO', 'CONAE', 'Success', 'Success'),
 (datetime.datetime(2018, 11, 15, 20, 46), 'F9 B5 B1047.2', 'KSC LC-39A', 'Es hail 2', 5300, 'GTO', 'Es hailSat', 'Success', 'Success'),
 (datetime.datetime(2018, 12, 3, 18, 34, 5), 'F9 B5 B1046.3', 'VAFB SLC-4E', 'SSO-A ', 4000, 'SSO', 'Spaceflight Industries', 'Success', 'Success'),
 (datetime.datetime(2018, 12, 5, 18, 16), 'F9 B5B1050', 'CCAFS SLC-40', 'SpaceX CRS-16', 2500, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Failure'),
 (datetime.datetime(2018, 12, 23, 13, 51), 'F9 B5B1054', 'CCAFS SLC-40', 'GPS III-01 ', 4400, 'MEO', 'USAF', 'Success ', 'No attempt'),
 (datetime.datetime(2019, 1, 11, 15, 31), 'F9 B5 B1049.2', 'VAFB SLC-4E', 'Iridium NEXT-8', 9600, 'Polar LEO', 'Iridium Communications', 'Success', 'Success'),
 (datetime.datetime(2019, 2, 22, 1, 45), 'F9 B5 B1048.3', 'CCAFS SLC-40', 'Nusantara Satu, Beresheet Moon lander, S5', 4850, 'GTO', 'PSN, SpaceIL / IAI', 'Success', 'Success'),
 (datetime.datetime(2019, 3, 2, 7, 49), 'F9 B5B1051.1', 'KSC LC-39A', 'Crew Dragon Demo-1, SpaceX CRS-17 ', 12055, 'LEO (ISS)', 'NASA (CCD) ', 'Success', 'Success'),
 (datetime.datetime(2019, 5, 4, 6, 48), 'F9 B5B1056.1 ', 'CCAFS SLC-40', 'SpaceX CRS-17, Starlink v0.9', 2495, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success'),
 (datetime.datetime(2019, 5, 24, 2, 30), 'F9 B5 B1049.3', 'CCAFS SLC-40', 'Starlink v0.9, RADARSAT Constellation', 13620, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2019, 6, 12, 14, 17), 'F9 B5 B1051.2 ', 'VAFB SLC-4E', 'RADARSAT Constellation, SpaceX CRS-18 ', 4200, 'SSO', 'Canadian Space Agency (CSA)', 'Success', 'Success'),
 (datetime.datetime(2019, 7, 25, 22, 1), 'F9 B5 B1056.2 ', 'CCAFS SLC-40', 'SpaceX CRS-18, AMOS-17 ', 2268, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success'),
 (datetime.datetime(2019, 8, 6, 23, 23), 'F9 B5 B1047.3 ', 'CCAFS SLC-40', 'AMOS-17, Starlink 1 v1.0 ', 6500, 'GTO', 'Spacecom', 'Success', 'No attempt '),
 (datetime.datetime(2019, 11, 11, 14, 56), 'F9 B5 B1048.4', 'CCAFS SLC-40', 'Starlink 1 v1.0, SpaceX CRS-19 ', 15600, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2019, 12, 5, 17, 29), 'F9 B5B1059.1', 'CCAFS SLC-40', 'SpaceX CRS-19, JCSat-18 / Kacific 1 ', 2617, 'LEO (ISS)', 'NASA (CRS), Kacific 1', 'Success', 'Success'),
 (datetime.datetime(2019, 12, 17, 0, 10), 'F9 B5 B1056.3 ', 'CCAFS SLC-40', 'JCSat-18 / Kacific 1, Starlink 2 v1.0 ', 6956, 'GTO', 'Sky Perfect JSAT, Kacific 1', 'Success', 'Success'),
 (datetime.datetime(2020, 1, 7, 2, 33), 'F9 B5 B1049.4', 'CCAFS SLC-40', 'Starlink 2 v1.0, Crew Dragon in-flight abort test ', 15600, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2020, 1, 19, 15, 30), 'F9 B5 B1046.4', 'KSC LC-39A', 'Crew Dragon in-flight abort test, Starlink 3 v1.0 ', 12050, 'Sub-orbital', 'NASA (CTS)', 'Success', 'No attempt'),
 (datetime.datetime(2020, 1, 29, 14, 7), 'F9 B5 B1051.3', 'CCAFS SLC-40', 'Starlink 3 v1.0, Starlink 4 v1.0 ', 15600, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2020, 2, 17, 15, 5), 'F9 B5 B1056.4', 'CCAFS SLC-40', 'Starlink 4 v1.0, SpaceX CRS-20', 15600, 'LEO', 'SpaceX', 'Success', 'Failure'),
 (datetime.datetime(2020, 3, 7, 4, 50), 'F9 B5 B1059.2', 'CCAFS SLC-40', 'SpaceX CRS-20, Starlink 5 v1.0 ', 1977, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success'),
 (datetime.datetime(2020, 3, 18, 12, 16), 'F9 B5 B1048.5', 'KSC LC-39A', 'Starlink 5 v1.0, Starlink 6 v1.0 ', 15600, 'LEO', 'SpaceX', 'Success', 'Failure'),
 (datetime.datetime(2020, 4, 22, 19, 30), 'F9 B5 B1051.4', 'KSC LC-39A', 'Starlink 6 v1.0, Crew Dragon Demo-2 ', 15600, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2020, 5, 30, 19, 22), 'F9 B5B1058.1 ', 'KSC LC-39A', 'Crew Dragon Demo-2, Starlink 7 v1.0 ', 12530, 'LEO (ISS)', 'NASA (CCDev)', 'Success', 'Success'),
 (datetime.datetime(2020, 6, 4, 1, 25), 'F9 B5 B1049.5', 'CCAFS SLC-40', 'Starlink 7 v1.0, Starlink 8 v1.0', 15600, 'LEO', 'SpaceX, Planet Labs', 'Success', 'Success'),
 (datetime.datetime(2020, 6, 13, 9, 21), 'F9 B5 B1059.3', 'CCAFS SLC-40', 'Starlink 8 v1.0, SkySats-16, -17, -18, GPS III-03 ', 15410, 'LEO', 'SpaceX, Planet Labs', 'Success', 'Success'),
 (datetime.datetime(2020, 6, 30, 20, 10, 46), 'F9 B5B1060.1', 'CCAFS SLC-40', 'GPS III-03, ANASIS-II', 4311, 'MEO', 'U.S. Space Force', 'Success', 'Success'),
 (datetime.datetime(2020, 7, 20, 21, 30), 'F9 B5 B1058.2 ', 'CCAFS SLC-40', 'ANASIS-II, Starlink 9 v1.0', 5500, 'GTO', 'Republic of Korea Army, Spaceflight Industries (BlackSky)', 'Success', 'Success'),
 (datetime.datetime(2020, 8, 7, 5, 12), 'F9 B5 B1051.5', 'KSC LC-39A', 'Starlink 9 v1.0, SXRS-1, Starlink 10 v1.0 ', 14932, 'LEO', 'SpaceX, Spaceflight Industries (BlackSky), Planet Labs', 'Success', 'Success'),
 (datetime.datetime(2020, 8, 18, 14, 31), 'F9 B5 B1049.6', 'CCAFS SLC-40', 'Starlink 10 v1.0, SkySat-19, -20, -21, SAOCOM 1B ', 15440, 'LEO', 'SpaceX, Planet Labs, PlanetIQ', 'Success', 'Success'),
 (datetime.datetime(2020, 8, 30, 23, 18), 'F9 B5 B1059.4', 'CCAFS SLC-40', 'SAOCOM 1B, GNOMES 1, Tyvak-0172', 3130, 'SSO', 'CONAE, PlanetIQ, SpaceX', 'Success', 'Success'),
 (datetime.datetime(2020, 9, 3, 12, 46, 14), 'F9 B5 B1060.2 ', 'KSC LC-39A', 'Starlink 11 v1.0, Starlink 12 v1.0 ', 15600, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2020, 10, 6, 11, 29, 34), 'F9 B5 B1058.3 ', 'KSC LC-39A', 'Starlink 12 v1.0, Starlink 13 v1.0 ', 15600, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2020, 10, 18, 12, 25, 57), 'F9 B5 B1051.6', 'KSC LC-39A', 'Starlink 13 v1.0, Starlink 14 v1.0 ', 15600, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2020, 10, 24, 15, 31, 34), 'F9 B5 B1060.3', 'CCAFS SLC-40', 'Starlink 14 v1.0, GPS III-04  ', 15600, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2020, 11, 5, 23, 24, 23), 'F9 B5B1062.1', 'CCAFS SLC-40', 'GPS III-04 , Crew-1', 4311, 'MEO', 'USSF', 'Success', 'Success'),
 (datetime.datetime(2020, 11, 16, 0, 27), 'F9 B5B1061.1 ', 'KSC LC-39A', 'Crew-1, Sentinel-6 Michael Freilich ', 12500, 'LEO (ISS)', 'NASA (CCP)', 'Success', 'Success'),
 (datetime.datetime(2020, 11, 21, 17, 17, 8), 'F9 B5B1063.1', 'VAFB SLC-4E', 'Sentinel-6 Michael Freilich, Starlink 15 v1.0 ', 1192, 'LEO', 'NASA / NOAA / ESA / EUMETSAT', 'Success', 'Success'),
 (datetime.datetime(2020, 11, 25, 2, 13), 'F9 B5 B1049.7 ', 'CCAFS SLC-40', 'Starlink 15 v1.0, SpaceX CRS-21', 15600, 'LEO', 'SpaceX', 'Success', 'Success'),
 (datetime.datetime(2020, 12, 6, 16, 17, 8), 'F9 B5 B1058.4 ', 'KSC LC-39A', 'SpaceX CRS-21', 2972, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success')]

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [23]:
%sql select distinct(launch_site) from spacextbl

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[('KSC LC-39A',), ('CCAFS SLC-40',), ('CCAFS LC-40',), ('VAFB SLC-4E',)]


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [27]:
%sql select * from spacextbl where launch_site like 'CCA%' and rownum<=5

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[(datetime.datetime(2010, 6, 4, 18, 45), 'F9 v1.0  B0003', 'CCAFS LC-40', 'Dragon Spacecraft Qualification Unit', 0, 'LEO', 'SpaceX', 'Success', 'Failure (parachute)'),
 (datetime.datetime(2010, 12, 8, 15, 43), 'F9 v1.0  B0004', 'CCAFS LC-40', 'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese', 0, 'LEO (ISS)', 'NASA (COTS) NRO', 'Success', 'Failure (parachute)'),
 (datetime.datetime(2012, 5, 22, 7, 44), 'F9 v1.0  B0005', 'CCAFS LC-40', 'Dragon demo flight C2', 525, 'LEO (ISS)', 'NASA (COTS)', 'Success', 'No attempt'),
 (datetime.datetime(2012, 10, 8, 0, 35), 'F9 v1.0  B0006', 'CCAFS LC-40', 'SpaceX CRS-1', 500, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt'),
 (datetime.datetime(2013, 3, 1, 15, 10), 'F9 v1.0  B0007', 'CCAFS LC-40', 'SpaceX CRS-2', 677, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt')]

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [28]:
%sql select sum(payload_mass__kg_) from spacextbl where customer ='NASA (CRS)'

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[(45596,)]

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [29]:
%sql select avg(payload_mass__kg_) from spacextbl where booster_version='F9 v1.1'

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[(Decimal('2928.4'),)]

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [40]:
%sql select min(date1) from spacextbl where landing_outcome like'%Success%'

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[(datetime.datetime(2015, 12, 22, 1, 29),)]

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [41]:
%sql select distinct(landing_outcome) from spacextbl

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[('Success (ground pad)',),
 ('Failure',),
 ('Failure (parachute)',),
 ('Controlled (ocean)',),
 ('Success (drone ship)',),
 ('No attempt',),
 ('Uncontrolled (ocean)',),
 ('Precluded (drone ship)',),
 ('No attempt ',),
 ('Success',),
 ('Failure (drone ship)',)]

In [42]:
%sql select booster_version from spacextbl where landing_outcome='Success (drone ship)' and payload_mass__kg_ between 4000 and 6000

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[('F9 FT B1022',), ('F9 FT B1026',), ('F9 FT  B1021.2',), ('F9 FT  B1031.2',)]

### Task 7




##### List the total number of successful and failure mission outcomes

In [48]:
%sql select count(*),mission_outcome from spacextbl group by mission_outcome

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[(1, 'Success (payload status unclear)'),
 (1, 'Success '),
 (98, 'Success'),
 (1, 'Failure (in flight)')]

### Task 8



##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [49]:
%sql select booster_version from spacextbl where payload_mass__kg_ =(select max(payload_mass__kg_)from spacextbl)

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[('F9 B5 B1048.4',),
 ('F9 B5 B1049.4',),
 ('F9 B5 B1051.3',),
 ('F9 B5 B1056.4',),
 ('F9 B5 B1048.5',),
 ('F9 B5 B1051.4',),
 ('F9 B5 B1049.5',),
 ('F9 B5 B1060.2 ',),
 ('F9 B5 B1058.3 ',),
 ('F9 B5 B1051.6',),
 ('F9 B5 B1060.3',),
 ('F9 B5 B1049.7 ',)]

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 4, 2) as month to get the months and substr(Date,7,4)='2015' for year.**

In [53]:
%sql select to_char(date1, 'Month'),landing_outcome,booster_version,launch_site from spacextbl where landing_outcome='Failure (drone ship)' and EXTRACT(YEAR FROM date1)=2015

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[('January  ', 'Failure (drone ship)', 'F9 v1.1 B1012', 'CCAFS LC-40'),
 ('April    ', 'Failure (drone ship)', 'F9 v1.1 B1015', 'CCAFS LC-40')]

### Task 10




##### Rank the  count of  successful landing_outcomes between the date 04-06-2010 and 20-03-2017 in descending order.

In [81]:
%sql select count(*),landing_outcome from spacextbl where (to_char(cast(date1 as date),'YYYY-MM-DD')) between '2010-06-04' and '2017-03-20' group by landing_outcome having landing_outcome like'%Succes%'order by count(*) desc

 * oracle://practice:***@localhost:1521/xe
0 rows affected.

[(5, 'Success (drone ship)'), (3, 'Success (ground pad)')]